### ISSUE TITLE
Unable to perform inference on custom model

### ISSUE THREAD

**Issue by alessiabertugli** [nabeel-oz/qlik-py-tools#130]
Hi,

I have trained my models for regression using Qlik Sense and qlik-py-tools, but I am unable to perform the inference correctly. 
I followed the guide and manually created the yaml file where I put this line at the beginning (and put the file in the right folder):

path: ../pretrained/MLPRegressor-GSCV.joblib

I saw that a pkl file is called from the documentation, but qlik-py-tools only generates a joblib file. 
When I run the inference code, I get the following error when trying to run the PyTools.Bulk_Predict function

Qlik side:
Connector response error: grpc::StatusCode::UNKNOWN: 'Exception iterating responses: 0'

Python side:
Traceback (most recent call last):
  File "C:\Users\qlik\qlik-py-tools-8.1\qlik-py-env\lib\site-packages\grpc\_server.py", line 453, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "__main__.py", line 714, in _misc
    response = handle.predict(load_script=True)
  File "C:\Users\qlik\qlik-py-tools-8.1\qlik-py-env\core\_common.py", line 130, in predict
    self._initiate(row_template, col_headers)
  File "C:\Users\qlik\qlik-py-tools-8.1\qlik-py-env\core\_common.py", line 257, in _initiate
    kwargs = self.request_df.loc[0, 'kwargs']
  File "C:\Users\qlik\qlik-py-tools-8.1\qlik-py-env\lib\site-packages\pandas\core\indexing.py", line 1418, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\qlik\qlik-py-tools-8.1\qlik-py-env\lib\site-packages\pandas\core\indexing.py", line 805, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\qlik\qlik-py-tools-8.1\qlik-py-env\lib\site-packages\pandas\core\indexing.py", line 929, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "C:\Users\qlik\qlik-py-tools-8.1\qlik-py-env\lib\site-packages\pandas\core\indexing.py", line 1850, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "C:\Users\qlik\qlik-py-tools-8.1\qlik-py-env\lib\site-packages\pandas\core\indexing.py", line 160, in _get_label
    return self.obj._xs(label, axis=axis)
  File "C:\Users\qlik\qlik-py-tools-8.1\qlik-py-env\lib\site-packages\pandas\core\generic.py", line 3737, in xs
    loc = self.index.get_loc(key)
  File "C:\Users\qlik\qlik-py-tools-8.1\qlik-py-env\lib\site-packages\pandas\core\indexes\base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

Can you help me, please?

**Comment by alessiabertugli** [comment]
I solved the problem. I was calling the wrong functions from Qlik Sense.
