### ISSUE TITLE
ModuleNotFoundError: No module named 'fbprophet'

### ISSUE THREAD

**Issue by martyquinn** [nabeel-oz/qlik-py-tools#80]
**Describe the bug**
I'm trying to get the SSE server running. The init seemed to run though 
A clear and concise description of the bug.
(root) C:\Users\quinnmx\dev\qlik-py-tools-6.2\qlik-py-tools-6.2>Qlik-Py-Start.bat
Traceback (most recent call last):
  File "__main__.py", line 30, in <module>
    from _prophet import ProphetForQlik
  File "C:\Users\quinnmx\dev\qlik-py-tools-6.2\qlik-py-tools-6.2\qlik-py-env\core\_prophet.py", line 16, in <module>
    from fbprophet import Prophet, plot
ModuleNotFoundError: No module named 'fbprophet'

**Environment:**
Windows 10 
Qlik Sense Desktop
 - OS [e.g. Windows Server, Linux]
 - Qlik Sense Enterprise/ Desktop/ Kubernetes/ QlikView
 - SSE Version

**Additional context**

**Comment by nabeel-oz** [comment]
Hi @martyquinn , 

The missing module means that there was an error during the initialization. Similar issues in the past have been due to the incorrect version of Python (this SSE requires Python 3.6), or issues with the Visual Studio Build Tools installation (double check the components required [here](https://github.com/nabeel-oz/qlik-py-tools#installation)). 

If that doesn't help I'll need to see the full error message from `Qlik-Py-Init` to understand what's wrong in your case. You can delete the `qlik-py-env` folder and re-run the initialization to check for errors.

**Comment by nabeel-oz** [comment]
Closing this issue due to inactivity.
