### ISSUE TITLE
Forecasting using Python(Pytools) in QlikSense Desktop

### ISSUE THREAD

**Issue by pratikchhapolika** [nabeel-oz/qlik-py-tools#86]
I am using QlikSense Desktop latest version and trying to run forecasting using Pytools.Prophet.

But it's not showing me the output. Here is the data and function I have used.
`PyTools.Prophet([Data_col.autoCalendar.Date],Avg(Shipments),'freq=M , debug=True'). I am not getting the forecast line.`

The Qlik py tools is in C:\Users\user-name\Documents\qlik-py-tools-6.2 folder and I start the file "Qlik-Py-Start.bat".

I start the .bat file and then open the Qliksense Desktop app which is in C:\Users\user-name\Documents\Qlik\Sense\Apps.

Its just showing this in command prompt:

When I run on this data with future values then Python throws an error.

REQUEST DATA FRAME: (22, 2) rows x cols

      ds       y
  0 1986-01-01  4009.0
  1 1986-02-01  4123.0
  2 1986-03-01  4493.0
  3 1986-04-01  4595.0
  4 1986-05-01  4245.0
  ...
       ds   y
 17 1987-06-01 NaN
18 1987-07-01 NaN
19 1987-08-01 NaN
20 1987-09-01 NaN
21 1987-10-01 NaN
INPUT DATA FRAME: (17, 2) rows x cols

      ds       y
0 1986-01-01  4009.0
1 1986-02-01  4123.0
2 1986-03-01  4493.0
3 1986-04-01  4595.0
4 1986-05-01  4245.0
... 
       ds               y 
12 1987-01-01   3000.0 
13 1987-02-01   2456.0 
14 1987-03-01   1234.0 
15 1987-04-01   3456.0 
16 1987-05-01   7878.0

2020-01-15 11:59:36,511 - ERROR - Exception iterating responses: object of type cannot be safely interpreted as an integer.

Traceback (most recent call last): File "C:\Users\user-name\Documents\qlik-py-tools-6.3\qlik-py-env\lib\site-packages\numpy\core\function_base.py", line 117, in linspace num = operator.index(num) TypeError: 'numpy.float64' object c annot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "C:\Users\user-name\Documents\qlik-py-tools-6.3\qlik-py-env\lib\site-packages\grpc_server.py", line 453, in _take_response_from_response_iterator return next(response_iterator), True

File "main.py", line 342, in _prophet forecast = predictor.predict() File "C:\Users\user-name\Documents\qlik-py-tools-6.3\qlik-py-env\core_prophet.py", line 272, in predict self.model.fit(self.input_df, **self.fit_kwargs)

File "C:\Users\user-name\Documents\qlik-py-tools-6.3\qlik-py-env\lib\site-packages\fbprophet\forecaster.py", line 1032, in fit self.set_changepoints()

File "C:\Users\user-name\Documents\qlik-py-tools-6.3\qlik-py-env\lib\site-packages\fbprophet\forecaster.py", line 347, in set_changepoints np.linspace(0, hist_size - 1, self.n_changepoints + 1)

File "<array_function internals>", line 6, in linspace

File "C:\Users\user-name\Documents\qlik-py-tools-6.3\qlik-py-env\lib\site-packages\numpy\core\function_base.py", line 121, in linspace .format(type(num)))

TypeError: object of type cannot be safely interpreted as an integer.

**Comment by ilyasjmd** [comment]
the latest version of numpy - 1.18.1 has this issue. you may need to uninstall this and install 1.17.5.
i faced this issue yesterday and resolved it by installing 1.17.5
i am not sure of how to uninstall numpy from the virtual machine. so i installed numpy 1.17.5 on my local machine and copied the files from local to virtual machine folder.

Local path: C:\Users\*********\AppData\Local\Programs\Python\Python36\Lib\site-packages
Virtual Path:  qlik-py-tools-6.3\qlik-py-tools-6.3\qlik-py-env\Lib\site-packages

Command to install numpy on local machine: 
run command prompt
pip install numpy==1.17.5

i think we can add this into "Qlik-Py-Init.bat" so that it installs the working version.

**Comment by nabeel-oz** [comment]
Thanks @ilyasjmd. 

Yes, I confirmed that there is an issue because of the latest release of numpy. I'll fix this in the next release, but for now you can fix your existing installation with these steps:

- Open a powershell window at qlik-py-tools-6.3\qlik-py-env\Scripts
- Run this command to activate the Python virtual environment: `.\activate.ps1`
- Downgrade numpy to the previous stable version: `pip install --upgrade numpy==1.17.5`
- Restart PyTools using the `Qlik-Py-Start` bat or ps1 file

![image](https://user-images.githubusercontent.com/21298843/72570292-a47ae980-3910-11ea-8c60-0e054215d379.png)

**Comment by pratikchhapolika** [comment]
After updating numpy version:

2020-01-17 18:05:39,316 - ERROR - Exception iterating responses: dictionary update sequence element #0 has length 3; 2 is required
Traceback (most recent call last):
  File "C:\Users\*****\Documents\qlik-py-tools-6.3\qlik-py-env\lib\site-packages\grpc\_server.py", line 453, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "__main__.py", line 339, in _prophet
    predictor = ProphetForQlik(request_list, context)
  File "C:\Users\*****\Documents\qlik-py-tools-6.3\qlik-py-env\core\_prophet.py", line 63, in __init__
    self._set_params()
  File "C:\Users\*****\Documents\qlik-py-tools-6.3\qlik-py-env\core\_prophet.py", line 394, in _set_params
    self.kwargs = dict([arg.split("=") for arg in args])
ValueError: dictionary update sequence element #0 has length 3; 2 is required

The data set is:
quarter   Shipments
1/1/1986    4009
2/1/1986    4123
3/1/1986    4493
4/1/1986    4595
5/1/1986    4245
6/1/1986    4321
7/1/1986    4522
8/1/1986    4806
9/1/1986    4799
10/1/1986   4900
11/1/1986   400
12/1/1986   5000
1/1/1987    3000
2/1/1987    2456
3/1/1987    1234
4/1/1987    3456
5/1/1987    7878
6/1/1987    
7/1/1987    
8/1/1987    

Formula:  PyTools.Prophet(Quarter,Avg(Shipments),'freq=M debug=true')

**Comment by nabeel-oz** [comment]
The arguments to the funding need to be separated by commas. 

```
PyTools.Prophet(Quarter,Avg(Shipments),'freq=M, debug=true')
```
